import type { Metadata } from "next";
import { Geist, Geist_Mono, Questrial } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Suspense } from "react";
import { Providers } from "@/redux/provider";
import Layout from "@/components/layout/Layout";
import Spinner from "@/components/spinner/Spinner";
import { useGetGlobalVariablesQuery } from "@/redux/services/app.service";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const questrial = Questrial({
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${questrial.className} antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const storedTheme = localStorage.getItem('theme') || 'dark';
                  document.documentElement.classList.add(storedTheme);
                } catch (e) {
                  document.documentElement.classList.add('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body suppressHydrationWarning>
        <ThemeProvider>
          <Providers>
            <Suspense fallback={<Spinner />}>
              <Layout modeKey="base">{children}</Layout>
            </Suspense>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
